=== yahya-galib/ProjetXML/Rendu/metro.dtd
<!ELEMENT metro (station*, ligne*)>

<!ELEMENT station (station_name, station_desc, emplacement, lignes)>
<!ATTLIST station id ID #REQUIRED>
<!ELEMENT station_name (#PCDATA)>
<!ELEMENT station_desc (#PCDATA)>
<!ELEMENT emplacement (station_lat, station_lon)>
<!ELEMENT station_lat (#PCDATA)>
<!ELEMENT station_lon (#PCDATA)>
<!ELEMENT lignes (lig*)>
<!ELEMENT lig EMPTY>
<!ATTLIST lig idref IDREF #REQUIRED>

<!ELEMENT ligne (nom_complet, route*)>
<!ATTLIST ligne id ID #REQUIRED>
<!ATTLIST ligne short_name CDATA #REQUIRED>
<!ELEMENT nom_complet (first,last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT last (#PCDATA)>
<!ELEMENT route (direction, arret*)>
<!ATTLIST route id ID #REQUIRED>
<!ELEMENT direction (#PCDATA)>
<!ELEMENT arret EMPTY>
<!ATTLIST arret idref IDREF #REQUIRED>
<!ATTLIST arret index CDATA #REQUIRED>

=== yahya-galib/ProjetXML/Rendu/output.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE gedcom SYSTEM "metro.dtd">
<metro> 
   <station id="S2212">
       <station_name>Château de Vincennes</station_name>
       <station_desc>Gare routière - 94080</station_desc>
       <emplacement>
           <station_lat>48.8443251443686</station_lat>
           <station_lon>2.44055234621182</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
       </lignes>
   </station>

   <station id="S2080">
       <station_name>Bérault</station_name>
       <station_desc>98 avenue de Paris - 94080</station_desc>
       <emplacement>
           <station_lat>48.8453687501573</station_lat>
           <station_lon>2.42824450962049</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
       </lignes>
   </station>

   <station id="S3068">
       <station_name>Saint-Mandé</station_name>
       <station_desc>180 avenue Galliéni - 94067</station_desc>
       <emplacement>
           <station_lat>48.8462382566208</station_lat>
           <station_lon>2.41899982810926</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
       </lignes>
   </station>

   <station id="S2924">
       <station_name>Porte de Vincennes</station_name>
       <station_desc>99 Cours de Vincennes - 75120</station_desc>
       <emplacement>
           <station_lat>48.8470165184191</station_lat>
           <station_lon>2.41081688233476</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
       </lignes>
   </station>

   <station id="S2716">
       <station_name>Nation</station_name>
       <station_desc>Terre-plein face au 3 place de la Nation - 75112</station_desc>
       <emplacement>
           <station_lat>48.8490101536482</station_lat>
           <station_lon>2.39766461279101</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
           <lig idref = "L1544644"/>
           <lig idref = "L2280310"/>
           <lig idref = "L2280360"/>
       </lignes>
   </station>

   <station id="S2988">
       <station_name>Reuilly-Diderot</station_name>
       <station_desc>Boulevard Diderot - 75112</station_desc>
       <emplacement>
           <station_lat>48.8473528769588</station_lat>
           <station_lon>2.38584254004024</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
           <lig idref = "L2280344"/>
       </lignes>
   </station>

   <station id="S2424">
       <station_name>Gare de Lyon</station_name>
       <station_desc>Rue de Bercy - 75112</station_desc>
       <emplacement>
           <station_lat>48.8446521509829</station_lat>
           <station_lon>2.37310814754528</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
           <lig idref = "L2280413"/>
       </lignes>
   </station>

   <station id="S2068">
       <station_name>Bastille</station_name>
       <station_desc>Rue de la Roquette - 75104</station_desc>
       <emplacement>
           <station_lat>48.8529756746542</station_lat>
           <station_lon>2.36921882444334</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
           <lig idref = "L2280297"/>
           <lig idref = "L2280344"/>
       </lignes>
   </station>

   <station id="S3080">
       <station_name>Saint-Paul Le Marais</station_name>
       <station_desc>Rivoli terre plein face au 10 rue de - 75104</station_desc>
       <emplacement>
           <station_lat>48.855134518235</station_lat>
           <station_lon>2.36133433906766</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
       </lignes>
   </station>

   <station id="S2464">
       <station_name>Hôtel de Ville</station_name>
       <station_desc>Rue du Renard - 75104</station_desc>
       <emplacement>
           <station_lat>48.8573559271695</station_lat>
           <station_lon>2.35207356685872</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
           <lig idref = "L2280382"/>
       </lignes>
   </station>

   <station id="S2224">
       <station_name>Châtelet</station_name>
       <station_desc>Théâtre du Châtelet - 75101</station_desc>
       <emplacement>
           <station_lat>48.8572036455044</station_lat>
           <station_lon>2.34722471105584</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
           <lig idref = "L2280284"/>
           <lig idref = "L2280325"/>
           <lig idref = "L2280382"/>
           <lig idref = "L2280413"/>
       </lignes>
   </station>

   <station id="S2592">
       <station_name>Louvre-Rivoli</station_name>
       <station_desc>Amiral de Coligny 8 rue de l' - 75101</station_desc>
       <emplacement>
           <station_lat>48.8608798575938</station_lat>
           <station_lon>2.3409732758179</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
       </lignes>
   </station>

   <station id="S2752">
       <station_name>Palais-Royal Musée du Louvre</station_name>
       <station_desc>Terre-plein face au 93 rue de Rivoli - 75101</station_desc>
       <emplacement>
           <station_lat>48.8633873850655</station_lat>
           <station_lon>2.33548383677237</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
           <lig idref = "L2280325"/>
       </lignes>
   </station>

   <station id="S3160">
       <station_name>Tuileries</station_name>
       <station_desc>210 rue de Rivoli - 75101</station_desc>
       <emplacement>
           <station_lat>48.8647801625001</station_lat>
           <station_lon>2.32909495442943</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
       </lignes>
   </station>

   <station id="S2260">
       <station_name>Concorde</station_name>
       <station_desc>Place de la Concorde - 75108</station_desc>
       <emplacement>
           <station_lat>48.8656780964178</station_lat>
           <station_lon>2.32119377180187</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
           <lig idref = "L2280344"/>
           <lig idref = "L2280396"/>
       </lignes>
   </station>

   <station id="S2184">
       <station_name>Champs-Elysées-Clémenceau</station_name>
       <station_desc>Clémenceau place - 75108</station_desc>
       <emplacement>
           <station_lat>48.8673665704698</station_lat>
           <station_lon>2.31419106339366</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
           <lig idref = "L2280400"/>
       </lignes>
   </station>

   <station id="S2392">
       <station_name>Franklin-Roosevelt</station_name>
       <station_desc>Palais de la Découverte - 75108</station_desc>
       <emplacement>
           <station_lat>48.8690104279376</station_lat>
           <station_lon>2.31025318089603</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
           <lig idref = "L2280360"/>
       </lignes>
   </station>

   <station id="S2436">
       <station_name>George V</station_name>
       <station_desc>118 avenue des Champs-Elysées - 75108</station_desc>
       <emplacement>
           <station_lat>48.8720456194264</station_lat>
           <station_lon>2.30076918564495</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
       </lignes>
   </station>

   <station id="S2196">
       <station_name>Charles de Gaulle-Etoile</station_name>
       <station_desc>Place Charles de Gaulle - 75108</station_desc>
       <emplacement>
           <station_lat>48.8739310942679</station_lat>
           <station_lon>2.2951272516501</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
           <lig idref = "L1544644"/>
           <lig idref = "L2280310"/>
       </lignes>
   </station>

   <station id="S2028">
       <station_name>Argentine</station_name>
       <station_desc>Rue des Acacias - 75117</station_desc>
       <emplacement>
           <station_lat>48.8756724859879</station_lat>
           <station_lon>2.28944416448145</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
       </lignes>
   </station>

   <station id="S2936">
       <station_name>Porte Maillot</station_name>
       <station_desc>Palais des Congrès - 75117</station_desc>
       <emplacement>
           <station_lat>48.878006176279</station_lat>
           <station_lon>2.28246564000133</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
       </lignes>
   </station>

   <station id="S2568">
       <station_name>Les Sablons Jardin d'acclimatation</station_name>
       <station_desc>Jardin d'Acclimatation - 92051</station_desc>
       <emplacement>
           <station_lat>48.8812991854911</station_lat>
           <station_lon>2.27191517601779</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
       </lignes>
   </station>

   <station id="S2832">
       <station_name>Pont de Neuilly</station_name>
       <station_desc>209 avenue Charles de Gaulle - 92051</station_desc>
       <emplacement>
           <station_lat>48.8855061094182</station_lat>
           <station_lon>2.25852747019736</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
       </lignes>
   </station>

   <station id="S2356">
       <station_name>Esplanade de la Défense</station_name>
       <station_desc>Quartier Saisons - 92062</station_desc>
       <emplacement>
           <station_lat>48.8883580601662</station_lat>
           <station_lon>2.2499372128628</station_lon>
       </emplacement>
       <lignes>
           <lig idref = "L2280236"/>
       </lignes>
   </station>

   <station id="S2516">
